/* App config for images
 */
const images = {
  onBoard: {
    page1: require('../assets/Onboard/page1.png'),
    page2: require('../assets/Onboard/page2.png'),
    page3: require('../assets/Onboard/page3.png'),
    page4: require('../assets/Onboard/page4.png'),
  },
  bottomBar: {
    calender: require('../assets/Bottombar/calender.png'),
    heart: require('../assets/Bottombar/heart.png'),
    message: require('../assets/Bottombar/message.png'),
    profile: require('../assets/Bottombar/profile.png'),
    search: require('../assets/Bottombar/search.png'),
  },
  global: {
    noData: require('../assets/Global/noData.json'),
    logo: require('../assets/Global/logo.png'),
    logoMini: require('../assets/Global/logoMini.png'),
  },
  socialLogin: {
    google: require('../assets/socialLogin/google.png'),
    apple: require('../assets/socialLogin/apple.png'),
    facebook: require('../assets/socialLogin/facebook.png'),
  },
  chooser: {
    google: require('../assets/Chooser/headphone.png'),
  },
  drawer: {
    drawer: require('../assets/drawer/drawer.png'),
    notification: require('../assets/drawer/notification.png'),
  },
  cardetails: {
    back: require('../assets/CarDetail/back.png'),
    white_heart: require('../assets/CarDetail/heart.png'),
    calender: require('../assets/CarDetail/calander.png'),
    pen: require('../assets/CarDetail/pen.png'),
    location: require('../assets/CarDetail/location.png'),
    seat: require('../assets/CarDetail/seat.png'),
    petrol: require('../assets/CarDetail/petrol.png'),
    cc: require('../assets/CarDetail/cc.png'),
    bigsmall: require('../assets/CarDetail/bigsmall.png'),
    auto: require('../assets/CarDetail/auto.png'),
    ac: require('../assets/CarDetail/Ac.png'),
    video: require('../assets/CarDetail/video.png'),
    signal: require('../assets/CarDetail/signal.png'),
    offers: require('../assets/CarDetail/offers.png'),
  },
  notification: {
    notification: require('../assets/Notification/notification.png'),
  },
  UploadPhoto: {
    profile: require('../assets/UploadPhoto/profile.png'),
    add: require('../assets/UploadPhoto/add.png'),
    flag: require('../assets/UploadPhoto/flag.png'),
    down: require('../assets/UploadPhoto/down.png'),
  },
  LicenseVerification: {
    profile: require('../assets/LicenseVerification/Profile.png'),
    building: require('../assets/LicenseVerification/building.png'),
    license: require('../assets/LicenseVerification/license.png'),
    licenseNumber: require('../assets/LicenseVerification/licenseNumber.png'),
    upload: require('../assets/LicenseVerification/upload.png'),
  },
  features: {
    AirConditioner: require('../assets/Features/AirConditioner.png'),
    Bluetooth: require('../assets/Features/Bluetooth.png'),
    WaterBottles: require('../assets/Features/WaterBottles.png'),
    USB: require('../assets/Features/USB.png'),
    Umbrella: require('../assets/Features/Umbrella.png'),
    Tissues: require('../assets/Features/Tissues.png'),
    ReverseCamera: require('../assets/Features/ReverseCamera.png'),
    PhoneHolder: require('../assets/Features/PhoneHolder.png'),
    ParkingSensor: require('../assets/Features/ParkingSensor.png'),
    MobileChargingCable: require('../assets/Features/MobileChargingCable.png'),
    GPS: require('../assets/Features/GPS.png'),
    FirstAidKit: require('../assets/Features/FirstAidKit.png'),
    EmergencyKit: require('../assets/Features/EmergencyKit.png'),
    DashCamera: require('../assets/Features/DashCamera.png'),
  },
  explore: {
    car: require('../assets/Explore/car.png'),
    img_card_heart: require('../assets/Explore/img_card_heart.png'),
    blackCar: require('../assets/Explore/blackCar.png'),
    star: require('../assets/Explore/star.png'),
    aux: require('../assets/Explore/auxCable.png'),
    bluetooth: require('../assets/Explore/bluetooth.png'),
    satelite: require('../assets/Explore/satelite.png'),
    calender: require('../assets/Explore/calender.png'),
    percentage: require('../assets/Explore/percentage.png'),
  },
  PickupChoose: {
    carDelivery: require('../assets/PickupChoose/carDelivery.png'),
    carPickup: require('../assets/PickupChoose/carPickup.png'),
    circle: require('../assets/PickupChoose/circle.png'),
    selfPickup: require('../assets/PickupChoose/selfPickup.png'),
  },
  Payment: {
    next: require('../assets/Payment/next.png'),
  },
  Confirm: {
    thirtyPlus: require('../assets/Confirm/thirtyPlus.png'),
    car: require('../assets/Confirm/car.png'),
    line: require('../assets/Confirm/line.png'),
  },
  BookingDetail: {
    pickup: require('../assets/BookingDetail/pickup.png'),
    return: require('../assets/BookingDetail/return.png'),
  },
  Profile: {
    profile: require('../assets/Profile/profile.png'),
    profileImage: require('../assets/Profile/profileImage.png'),
    verify: require('../assets/Profile/verify.png'),
    logout: require('../assets/Profile/logout.png'),
    facebook: require('../assets/Profile/facebook.png'),
    instagram: require('../assets/Profile/instagram.png'),
    google: require('../assets/Profile/google.png'),
    man: require('../assets/Profile/man.png'),
    headphone: require('../assets/Profile/headphone.png'),
    setting: require('../assets/Profile/setting.png'),
    questionMark: require('../assets/Profile/questionMark.png'),
    pen: require('../assets/Profile/pen.png'),
    heart: require('../assets/Profile/heart.png'),
    userImage: require('../assets/Profile/userImage.png'),
  },
  ProfileVerification: {
    profile: require('../assets/ProfileVerification/Profile.png'),
    call: require('../assets/ProfileVerification/call.png'),
    card: require('../assets/ProfileVerification/card.png'),
  },
  PaymentDetails: {
    masterCard: require('../assets/PaymentDetails/masterCard.png'),
    visaCard: require('../assets/PaymentDetails/visa.png'),
    greenCard: require('../assets/PaymentDetails/greenMasterCard.png'),
  },
  Message: {
    headerImage: require('./../assets/Message/send.png'),
  },
  Host: {
    headingImage: require('./../assets/Host/headingImage.png'),
    flag: require('./../assets/Host/flag.png'),
    addImage: require('./../assets/Host/addImage.png'),
    key: require('./../assets/Host/key.png'),
    lock: require('./../assets/Host/lock.png'),
    mask: require('./../assets/Host/mask.png'),
    back: require('./../assets/Host/back.png'),
    tissues: require('./../assets/Host/tissues.png'),
    toolKit: require('./../assets/Host/toolKit.png'),
    video: require('./../assets/Host/video.png'),
    reverseCamera: require('./../assets/Host/reverseCamera.png'),
    phoneHolder: require('./../assets/Host/phoneHolder.png'),
    parkingSensor: require('./../assets/Host/parkingSensor.png'),
    gps: require('./../assets/Host/gps.png'),
    firstAid: require('./../assets/Host/firstAid.png'),
    chargingCable: require('./../assets/Host/chargingCable.png'),
    bluetooth: require('./../assets/Host/bluetooth.png'),
    auxCable: require('./../assets/Host/auxCable.png'),
    airConditioner: require('./../assets/Host/airConditioner.png'),
  },
};

export default images;
